---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен соответствовать законодательным актам
  - Пользователь должен иметь возможность оформлять заказ
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность прелистывать старицы каталога товаров
  - В каталоге и на странице товара должны выводиться название, рейтинг, цена со скидкой и без
  - Пользователь должен иметь возможность добавить товар в корзину и продолжить выбирать товары в каталоге
